
export type Language = 'en' | 'ja' | 'zh' | 'my' | 'ko';

export const CATEGORY_KEYS = ['Cooking Ingredients', 'Food & Drinks', 'Clothing', 'Electronics', 'Others'];

export type Currency = 'USD' | 'JPY' | 'CNY' | 'MMK' | 'KRW' | 'SGD';

export const CURRENCY_OPTIONS: {value: Currency, label: string, symbol: string}[] = [
  { value: 'USD', label: 'USD ($)', symbol: '$' },
  { value: 'JPY', label: 'JPY (¥)', symbol: '¥' },
  { value: 'CNY', label: 'CNY (¥)', symbol: '¥' },
  { value: 'MMK', label: 'MMK (K)', symbol: 'K' },
  { value: 'KRW', label: 'KRW (₩)', symbol: '₩' },
  { value: 'SGD', label: 'SGD (S$)', symbol: 'S$' },
];

export const TRANSLATIONS = {
  en: {
    appName: 'SmartShop',
    all: 'All Items',
    search: 'Search items...',
    filter: 'Filter:',
    toBuy: 'To Buy',
    low: 'Low Stock',
    inStock: 'In Stock',
    price: 'Price',
    priceRange: 'Price Range',
    min: 'Min',
    max: 'Max',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    currency: 'Currency',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    close: 'Close',
    save: 'Save Item',
    delete: 'Delete',
    cancel: 'Cancel',
    edit: 'Edit Item',
    create: 'New Item',
    mediaTitle: 'Photos & Videos',
    uploadTip: 'Upload a photo to automatically fill details using AI!',
    analyzing: 'Analyzing...',
    nameLabel: 'Item Name',
    catLabel: 'Category',
    priceLabel: 'Price',
    storeLabel: 'Store / Location',
    statusLabel: 'Status',
    noteLabel: 'Notes',
    dontKnow: "Don't know",
    noItems: 'No items found',
    emptyState: 'Try adjusting your filters or search query.',
    createFirst: 'Create First Item',
    markBought: 'Mark Bought',
    addList: 'Add to List',
    confirmDelete: 'Are you sure you want to delete this item?',
    addMedia: 'Add Media',
    recycleBin: 'Recycle Bin',
    openRecycleBin: 'Open Recycle Bin',
    restore: 'Restore',
    deletePermanently: 'Delete Permanently',
    emptyBin: 'Empty Bin',
    noTrashItems: 'Trash is empty',
    trashTip: 'Items in trash will be automatically deleted after 30 days.',
    itemMovedToTrash: 'Item moved to trash',
    undo: 'Undo',
    storage: 'Storage',
    used: 'Used',
    available: 'Available',
    footerCreatedBy: 'Created by',
    footerEmailPrompt: 'Feel free to email me if you have any ideas for this web app.',
    footerClickHere: 'Click here.',
    share: 'Share',
    shareSuccess: 'Link copied to clipboard!',
    shareWarning: 'Link generated. Note: Photos/Videos are not shared.',
    itemImported: 'Shared item imported!',
    categories: {
      'Cooking Ingredients': 'Cooking Ingredients',
      'Food & Drinks': 'Food & Drinks',
      'Clothing': 'Clothing',
      'Electronics': 'Electronics',
      'Others': 'Others'
    }
  },
  ja: {
    appName: 'SmartShop',
    all: 'すべて',
    search: '検索...',
    filter: 'フィルター:',
    toBuy: '買うもの',
    low: '残りわずか',
    inStock: '在庫あり',
    price: '価格',
    min: '最小',
    max: '最大',
    settings: '設定',
    theme: 'テーマ',
    language: '言語',
    currency: '通貨',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    close: '閉じる',
    save: '保存',
    delete: '削除',
    cancel: 'キャンセル',
    edit: '編集',
    create: '新規作成',
    mediaTitle: '写真・動画',
    uploadTip: '写真をアップロードするとAIが自動入力します！',
    analyzing: '解析中...',
    nameLabel: '商品名',
    catLabel: 'カテゴリー',
    priceLabel: '価格',
    storeLabel: '店 / 場所',
    statusLabel: '状態',
    noteLabel: 'メモ',
    dontKnow: "不明",
    noItems: 'アイテムが見つかりません',
    emptyState: 'フィルターや検索条件を変更してください。',
    createFirst: '最初のアイテムを作成',
    markBought: '購入済みにする',
    addList: 'リストに追加',
    confirmDelete: '本当に削除しますか？',
    addMedia: 'メディア追加',
    recycleBin: 'ゴミ箱',
    openRecycleBin: 'ゴミ箱を開く',
    restore: '復元',
    deletePermanently: '完全に削除',
    emptyBin: 'ゴミ箱を空にする',
    noTrashItems: 'ゴミ箱は空です',
    trashTip: 'アイテムは30日後に自動的に削除されます。',
    itemMovedToTrash: 'ゴミ箱に移動しました',
    undo: '元に戻す',
    storage: 'ストレージ',
    used: '使用中',
    available: '利用可能',
    footerCreatedBy: '作成者:',
    footerEmailPrompt: 'ご意見やアイデアがございましたら、お気軽にメールください。',
    footerClickHere: 'ここをクリック',
    share: '共有',
    shareSuccess: 'リンクをコピーしました！',
    shareWarning: 'リンクを作成しました。注意：写真や動画は共有されません。',
    itemImported: '共有アイテムを読み込みました！',
    categories: {
      'Cooking Ingredients': '食材',
      'Food & Drinks': '食品・飲料',
      'Clothing': '衣類',
      'Electronics': '家電',
      'Others': 'その他'
    }
  },
  zh: {
    appName: 'SmartShop',
    all: '所有物品',
    search: '搜索...',
    filter: '筛选:',
    toBuy: '待购买',
    low: '库存不足',
    inStock: '有库存',
    price: '价格',
    min: '最小',
    max: '最大',
    settings: '设置',
    theme: '主题',
    language: '语言',
    currency: '货币',
    light: '浅色',
    dark: '深色',
    system: '跟随系统',
    close: '关闭',
    save: '保存',
    delete: '删除',
    cancel: '取消',
    edit: '编辑',
    create: '新建物品',
    mediaTitle: '照片与视频',
    uploadTip: '上传照片，AI将自动填写详情！',
    analyzing: '分析中...',
    nameLabel: '名称',
    catLabel: '类别',
    priceLabel: '价格',
    storeLabel: '商店 / 地点',
    statusLabel: '状态',
    noteLabel: '备注',
    dontKnow: "未知",
    noItems: '未找到物品',
    emptyState: '请尝试调整筛选或搜索条件。',
    createFirst: '创建第一个物品',
    markBought: '标记为已购',
    addList: '加入清单',
    confirmDelete: '确定要删除此物品吗？',
    addMedia: '添加媒体',
    recycleBin: '回收站',
    openRecycleBin: '打开回收站',
    restore: '恢复',
    deletePermanently: '永久删除',
    emptyBin: '清空回收站',
    noTrashItems: '回收站为空',
    trashTip: '物品将在30天后自动删除。',
    itemMovedToTrash: '物品已移至回收站',
    undo: '撤销',
    storage: '存储空间',
    used: '已用',
    available: '可用',
    footerCreatedBy: '创建者:',
    footerEmailPrompt: '如果您有任何想法，请随时发邮件给我。',
    footerClickHere: '点击这里',
    share: '分享',
    shareSuccess: '链接已复制！',
    shareWarning: '链接已生成。注意：照片/视频无法共享。',
    itemImported: '已导入分享的物品！',
    categories: {
      'Cooking Ingredients': '烹饪原料',
      'Food & Drinks': '食品饮料',
      'Clothing': '服装',
      'Electronics': '电子产品',
      'Others': '其他'
    }
  },
  my: {
    appName: 'SmartShop',
    all: 'ပစ္စည်းအားလုံး',
    search: 'ရှာဖွေရန်...',
    filter: 'စစ်ထုတ်ရန်:',
    toBuy: 'ဝယ်ရန်',
    low: 'လက်ကျန်နည်း',
    inStock: 'ရှိသည်',
    price: 'ဈေးနှုန်း',
    min: 'အနည်းဆုံး',
    max: 'အများဆုံး',
    settings: 'ဆက်တင်များ',
    theme: 'အသွင်အပြင်',
    language: 'ဘာသာစကား',
    currency: 'ငွေကြေး',
    light: 'အလင်း',
    dark: 'အမှောင်',
    system: 'System အတိုင်း',
    close: 'ပိတ်ရန်',
    save: 'သိမ်းဆည်းရန်',
    delete: 'ဖျက်ရန်',
    cancel: 'မလုပ်တော့ပါ',
    edit: 'ပြင်ဆင်ရန်',
    create: 'အသစ်ဖန်တီးရန်',
    mediaTitle: 'ဓာတ်ပုံနှင့်ဗီဒီယိုများ',
    uploadTip: 'ဓာတ်ပုံတင်ပြီး AI ဖြင့်အချက်အလက်များကို အလိုအလျောက်ဖြည့်ပါ!',
    analyzing: 'လေ့လာဆန်းစစ်နေသည်...',
    nameLabel: 'ပစ္စည်းအမည်',
    catLabel: 'အမျိုးအစား',
    priceLabel: 'ဈေးနှုန်း',
    storeLabel: 'ဆိုင် / နေရာ',
    statusLabel: 'အခြေအနေ',
    noteLabel: 'မှတ်ချက်များ',
    dontKnow: "မသိပါ",
    noItems: 'ပစ္စည်းမတွေ့ပါ',
    emptyState: 'စစ်ထုတ်မှုများ သို့မဟုတ် ရှာဖွေမှုကို ပြင်ဆင်ကြည့်ပါ။',
    createFirst: 'ပထမဆုံးပစ္စည်းကို ဖန်တီးပါ',
    markBought: 'ဝယ်ပြီးကြောင်းမှတ်သားမည်',
    addList: 'စာရင်းထဲထည့်မည်',
    confirmDelete: 'ဤပစ္စည်းကို ဖျက်မည်မှာ သေချာပါသလား?',
    addMedia: 'မီဒီယာထည့်ရန်',
    recycleBin: 'အမှိုက်ပုံး',
    openRecycleBin: 'အမှိုက်ပုံးဖွင့်ရန်',
    restore: 'ပြန်လည်ရယူရန်',
    deletePermanently: 'အပြီးတိုင်ဖျက်ရန်',
    emptyBin: 'အမှိုက်ပုံးရှင်းရန်',
    noTrashItems: 'အမှိုက်ပုံး ရှင်းနေပါသည်',
    trashTip: 'ပစ္စည်းများကို ရက် ၃၀ ကြာလျှင် အလိုအလျောက် ဖျက်ပါမည်။',
    itemMovedToTrash: 'ပစ္စည်းကို အမှိုက်ပုံးသို့ ရွှေ့လိုက်ပါပြီ',
    undo: 'ပြန်သွားရန်',
    storage: 'သိုလှောင်ခန်း',
    used: 'သုံးပြီး',
    available: 'ကျန်ရှိ',
    footerCreatedBy: 'ဖန်တီးသူ -',
    footerEmailPrompt: 'ဤ Web App အတွက် အကြံဉာဏ်များရှိပါက ကျွန်ုပ်ထံ အီးမေးလ်ပေးပို့နိုင်ပါသည်။',
    footerClickHere: 'ဒီမှာနှိပ်ပါ',
    share: 'မျှဝေရန်',
    shareSuccess: 'လင့်ခ်ကို ကူးယူပြီးပါပြီ!',
    shareWarning: 'လင့်ခ်ထုတ်ပြီးပါပြီ။ ဓာတ်ပုံ/ဗီဒီယိုများ မပါဝင်ပါ။',
    itemImported: 'မျှဝေထားသောပစ္စည်းကို ထည့်သွင်းပြီးပါပြီ!',
    categories: {
      'Cooking Ingredients': 'ချက်ပြုတ်ပစ္စည်းများ',
      'Food & Drinks': 'အစားအသောက်',
      'Clothing': 'အဝတ်အစား',
      'Electronics': 'လျှပ်စစ်ပစ္စည်း',
      'Others': 'အခြား'
    }
  },
  ko: {
    appName: 'SmartShop',
    all: '모든 항목',
    search: '검색...',
    filter: '필터:',
    toBuy: '구매 예정',
    low: '재고 부족',
    inStock: '재고 있음',
    price: '가격',
    priceRange: '가격 범위',
    min: '최소',
    max: '최대',
    settings: '설정',
    theme: '테마',
    language: '언어',
    currency: '통화',
    light: '라이트',
    dark: '다크',
    system: '시스템',
    close: '닫기',
    save: '저장',
    delete: '삭제',
    cancel: '취소',
    edit: '편집',
    create: '새 항목',
    mediaTitle: '사진 및 동영상',
    uploadTip: '사진을 업로드하면 AI가 자동으로 세부 정보를 입력합니다!',
    analyzing: '분석 중...',
    nameLabel: '상품명',
    catLabel: '카테고리',
    priceLabel: '가격',
    storeLabel: '상점 / 위치',
    statusLabel: '상태',
    noteLabel: '메모',
    dontKnow: "모름",
    noItems: '항목을 찾을 수 없습니다',
    emptyState: '필터나 검색어를 조정해 보세요.',
    createFirst: '첫 번째 항목 만들기',
    markBought: '구매 완료 표시',
    addList: '목록에 추가',
    confirmDelete: '이 항목을 삭제하시겠습니까?',
    addMedia: '미디어 추가',
    recycleBin: '휴지통',
    openRecycleBin: '휴지통 열기',
    restore: '복원',
    deletePermanently: '영구 삭제',
    emptyBin: '휴지통 비우기',
    noTrashItems: '휴지통이 비어 있습니다',
    trashTip: '항목은 30일 후 자동으로 삭제됩니다.',
    itemMovedToTrash: '항목이 휴지통으로 이동되었습니다',
    undo: '실행 취소',
    storage: '저장 공간',
    used: '사용됨',
    available: '사용 가능',
    footerCreatedBy: '제작:',
    footerEmailPrompt: '이 앱에 대한 아이디어가 있으시면 언제든지 이메일을 보내주세요.',
    footerClickHere: '여기를 클릭하세요',
    share: '공유',
    shareSuccess: '링크가 복사되었습니다!',
    shareWarning: '링크가 생성되었습니다. 주의: 사진/동영상은 공유되지 않습니다.',
    itemImported: '공유된 항목을 가져왔습니다!',
    categories: {
      'Cooking Ingredients': '요리 재료',
      'Food & Drinks': '식음료',
      'Clothing': '의류',
      'Electronics': '전자제품',
      'Others': '기타'
    }
  }
};
